title: afcrowther
email: afcrowther@icloud.com
description: >- # this means to ignore newlines until "baseurl:"
  The personal website of Adam Crowther. Revolves mostly around
  a blog of my learnings and projects in the fields of
  programming and computer science.
twitter_username: afcrowther
github_username: afcrowther
minimal_mistakes_skin: default
search: true
locale: en-GB

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
breadcrumbs: true
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: UTC
comments:
  provider: "disqus"
  disqus:
    shortname: "blog-iyhtp2xgw8"
twitter: afcrowther

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Adam Crowther"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Just a software developer looking for a place to document the things he learns."
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/afcrowther"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/afcrowther"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/afcrowther"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/afcrowther"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/afcrowther"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/afcrowther"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
